name: cs396
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.3.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bleach=4.1.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - cryptography=3.4.7
  - cycler=0.10.0
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - fonttools=4.25.0
  - freetype=2.10.4
  - icu=58.1
  - idna=3.1
  - importlib-metadata=4.8.1
  - intel-openmp=2021.3.0
  - ipykernel=6.4.1
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=3.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=7.0.3
  - jupyter_core=4.8.1
  - jupyter_server=1.11.0
  - jupyterlab=3.1.13
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.8.1
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libcxx=12.0.1
  - libffi=3.4.2
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclassic=0.3.2
  - nbclient=0.5.4
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.4.4
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.3
  - pandoc=2.14.2
  - pandocfilters=1.5.0
  - parso=0.8.2
  - patsy=0.5.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.4
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.10.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.1
  - pyzmq=22.3.0
  - readline=8.1
  - requests=2.26.0
  - requests-unixsocket=0.2.0
  - scipy=1.7.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - terminado=0.12.1
  - testpath=0.5.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.0
  - tzdata=2021a
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - wheel=0.37.0
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - appnope=0.1.2
    - libgfortran=3.0.1
    - apyori==1.1.2
    - click==8.0.1
    - joblib==1.1.0
    - nltk==3.6.3
    - polyglot==16.7.4
    - pycld2==0.41
    - pyicu==2.7.4
    - regex==2021.9.30
    - scikit-learn==1.0.1
    - sklearn==0.0
    - textblob==0.15.3
    - threadpoolctl==3.0.0
    - tqdm==4.62.3
